### ISSUE TITLE
Deploy online 101

### ISSUE THREAD

**Issue by ghost** [codex-academy/Nelisa#17]
Please can you clarify the steps needed for package.json file modifications before deployment to Heroku.

When typing `npm --save <module_name>` it returns npm usage as if it doesn't recognize the specific command I just ran.

I have included the text below :
<code>Please note:

```
You applications package.json file’s dependencies sections should contain all the modules your application depends on. So that Heroku knows which modules to install. Installing modules using npm --save <module_name> will keep your package.json up to date.

The dependencies section of your application’s package.json file should contain all the modules your application depends on; Heroku will use it to install your modules. When you’re developing your application, installing modules using npm install --save <module_name>. This adds the module(s) to your package.json so that it’s kept up to date.
```

</code>

**Comment by SteveBarnett** [comment]
@R2D2-12 Oops, good catch, thank you! The command should be `npm install --save <module_name>`, as it is further down that page. I've just updated the docs.
